[package]
name = "day1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "day1-p1"
path = "src/day1-p1.rs"

[[bin]]
name = "day1-p2"
path = "src/day1-p2.rs"

[dependencies]
